workflows:
  android-manual-build:
    name: Android Manual Build

    environment:
      java: 17

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true

    scripts:
      - name: Make gradlew executable
        script: chmod +x ./gradlew

      - name: Build debug APK
        script: |
          if [ ! -z "$KEYSTORE_BASE64" ]; then
            echo $KEYSTORE_BASE64 | base64 --decode > /tmp/keystore.jks
            export CM_KEYSTORE_PATH=/tmp/keystore.jks
          fi
          ./gradlew assembleDebug
          echo "Build version: $(grep "versionName" app/build.gradle | awk '{print $2}' | tr -d '\"')"
          echo "Build code: $(grep "versionCode" app/build.gradle | awk '{print $2}')"

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/mapping.txt